import { Container } from "@mantine/core";
import Head from "next/head";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hi</h1>
      </main>

      <footer></footer>
    </Container>
  );
}
