import { Container } from "@mantine/core";
import Head from "next/head";

import { useUser } from "@supabase/auth-helpers-react";
import { setCookie } from "cookies-next";
import { useEffect } from "react";

import FacebookMessengerPlugin from "../components/FacebookMessengerPlugin";

export default function Home() {
  const user = useUser();

  useEffect(() => {
    if (user) {
      setCookie("current_user", user.id);
    }
  }, [user]);

  return (
    <Container>
      <Head key={"account-page"}>
        <title>Your Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Onboarding Week 3</h1>
      </main>

      <footer>
        <FacebookMessengerPlugin />
      </footer>
    </Container>
  );
}
