import Head from "next/head";
import { Container, Stack, Text } from "@mantine/core";
import SignupPage from "../components/SignupPage";

export default function SignUp() {
  return (
    <Container>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Stack style={{ height: "100vh" }} align="center" justify="center">
          <Text weight={700} size="xl">
            Sign Up
          </Text>
          <SignupPage />
        </Stack>
      </main>

      <footer></footer>
    </Container>
  );
}
