import { NextPage } from "next";

import Head from "next/head";
import { Container } from "@mantine/core";

import { User } from "@supabase/supabase-js";
import { withPageAuth } from "@supabase/auth-helpers-nextjs";

const Profile: NextPage<{ user: User }> = ({ user }) => {
  console.log(user);
  return (
    <Container>
      <Head key={"account-page"}>
        <title>Your Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{user.email}</h1>
      </main>

      <footer></footer>
    </Container>
  );
};

export default Profile;

export const getServerSideProps = withPageAuth({
  redirectTo: "/signin",
  async getServerSideProps(ctx, supabase) {
    const {
      data: { user },
    } = await supabase.auth.getUser();
    console.log(user);
    return {
      props: { user: user },
    };
  },
});
