import { NextPage } from "next";

import Head from "next/head";
import { Container } from "@mantine/core";

import { User } from "@supabase/supabase-js";
import { withPageAuth } from "@supabase/auth-helpers-nextjs";

import ImageUpload from "../../components/ImageUpload";
import UserList from "../../components/UserList";
import KeywordSearchImageUpload from "../../components/KeywordSearchImageUpload";

import { Profile } from "../../types/TProfile";

const Profile: NextPage<{ user: User; profileList: Profile[] }> = ({
  user,
  profileList,
}) => {
  return (
    <Container>
      <Head key={"account-page"}>
        <title>Your Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome, {user.email}</h1>
        <KeywordSearchImageUpload userId={user.id} />
        <ImageUpload user={user} />
        <UserList profileList={profileList} userId={user.id} />
      </main>

      <footer></footer>
    </Container>
  );
};

export default Profile;

export const getServerSideProps = withPageAuth({
  redirectTo: "/signin",
  async getServerSideProps(ctx, supabase) {
    const {
      data: { user },
    } = await supabase.auth.getUser();

    const { data: user_profiles } = await supabase
      .from("user_profiles")
      .select()
      .neq("id", user?.id);

    return {
      props: { user: user, profileList: user_profiles },
    };
  },
});
